packages:
  - app/*
  - packages/*
  - tooling/*

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  '@tarojs/binding': false
  '@tarojs/cli': false
  core-js: false
  core-js-pure: false
  esbuild: true
